api_controllers:
    resource:
        path: ../src/Application/Controller/Api
        namespace: App\Application\Controller\Api
    prefix: /api
    type: attribute

web_controllers:
    resource:
        path: ../src/Application/Controller/Web
        namespace: App\Application\Controller\Web
    type: attribute

